packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^5
  "@types/node": ^22.13.14
  "@trpc/server": ^11.7.2
  "@libsql/client": 0.15.15
  libsql: 0.5.22
  "@trpc/client": ^11.7.2
