/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolumesRouteImport } from './routes/volumes'
import { Route as SnapshotsRouteImport } from './routes/snapshots'
import { Route as SandboxAgentRouteImport } from './routes/sandbox-agent'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntegrationsIndexRouteImport } from './routes/integrations/index'
import { Route as IntegrationsCreateRouteImport } from './routes/integrations/create'

const VolumesRoute = VolumesRouteImport.update({
  id: '/volumes',
  path: '/volumes',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotsRoute = SnapshotsRouteImport.update({
  id: '/snapshots',
  path: '/snapshots',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxAgentRoute = SandboxAgentRouteImport.update({
  id: '/sandbox-agent',
  path: '/sandbox-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsCreateRoute = IntegrationsCreateRouteImport.update({
  id: '/integrations/create',
  path: '/integrations/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/sandbox': typeof SandboxRoute
  '/sandbox-agent': typeof SandboxAgentRoute
  '/snapshots': typeof SnapshotsRoute
  '/volumes': typeof VolumesRoute
  '/integrations/create': typeof IntegrationsCreateRoute
  '/integrations': typeof IntegrationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/sandbox': typeof SandboxRoute
  '/sandbox-agent': typeof SandboxAgentRoute
  '/snapshots': typeof SnapshotsRoute
  '/volumes': typeof VolumesRoute
  '/integrations/create': typeof IntegrationsCreateRoute
  '/integrations': typeof IntegrationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/sandbox': typeof SandboxRoute
  '/sandbox-agent': typeof SandboxAgentRoute
  '/snapshots': typeof SnapshotsRoute
  '/volumes': typeof VolumesRoute
  '/integrations/create': typeof IntegrationsCreateRoute
  '/integrations/': typeof IntegrationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/sandbox'
    | '/sandbox-agent'
    | '/snapshots'
    | '/volumes'
    | '/integrations/create'
    | '/integrations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/sandbox'
    | '/sandbox-agent'
    | '/snapshots'
    | '/volumes'
    | '/integrations/create'
    | '/integrations'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/sandbox'
    | '/sandbox-agent'
    | '/snapshots'
    | '/volumes'
    | '/integrations/create'
    | '/integrations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  SandboxRoute: typeof SandboxRoute
  SandboxAgentRoute: typeof SandboxAgentRoute
  SnapshotsRoute: typeof SnapshotsRoute
  VolumesRoute: typeof VolumesRoute
  IntegrationsCreateRoute: typeof IntegrationsCreateRoute
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volumes': {
      id: '/volumes'
      path: '/volumes'
      fullPath: '/volumes'
      preLoaderRoute: typeof VolumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshots': {
      id: '/snapshots'
      path: '/snapshots'
      fullPath: '/snapshots'
      preLoaderRoute: typeof SnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox-agent': {
      id: '/sandbox-agent'
      path: '/sandbox-agent'
      fullPath: '/sandbox-agent'
      preLoaderRoute: typeof SandboxAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/create': {
      id: '/integrations/create'
      path: '/integrations/create'
      fullPath: '/integrations/create'
      preLoaderRoute: typeof IntegrationsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  SandboxRoute: SandboxRoute,
  SandboxAgentRoute: SandboxAgentRoute,
  SnapshotsRoute: SnapshotsRoute,
  VolumesRoute: VolumesRoute,
  IntegrationsCreateRoute: IntegrationsCreateRoute,
  IntegrationsIndexRoute: IntegrationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
